### PR TITLE
Update for Elm 0.19

### PR DESCRIPTION
**Pull request by xtian**

### CODE REVIEW

**Comment by xtian** [comment]
ping @lukewestby

**Comment by lukewestby** [comment]
hey @xtian, thank you for this! i'll merge and publish after i finish ellie this morning.

**Comment by xtian** [comment]
@lukewestby No prob! Got the tests passing on CI. Let me know if you'd like any changes made :)

**Comment by lukewestby** [comment]
this is perfect, thank you so much

**Comment by lukewestby** [comment]
@xtian published. let me know if you want me to add you as a collaborator on this repo so you don't have to wait on me for stuff like this

**Pull request merged**
